name:  Specification Proposal
description: Action Item submission
title: "[Spec-Proposal]"
labels: ["Spec-Proposal"]
projects: ["Add project"]
assignees: seanmcilroy29
body:
  - type: textarea
    id: scope
    attributes:
      label: Define the scope of the project
      description: Define the scope of the project
      placeholder: Define the scope of the project
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: Problem-statement
    attributes:
      label: Problem statement
      description: Problem statement
      placeholder: Problem statement
      value: "Add details"
    validations:
      required: true
