name:  Specification Proposal
description: Action Item submission
title: "[Spec-Proposal]"
labels: ["Spec-Proposal"]
projects: ["Add project"]
assignees: seanmcilroy29
body:
  - type: textarea
    id: Project-Title
    attributes:
      label: Project Title
      description: Project Title
      placeholder: Project Title
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: Project-Description
    attributes:
      label: Project-Description
      description: Project-Description
      placeholder: Project-Description
      value: "The goals of the project"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Define the scope of the project
      description: Define the scope of the project
      placeholder: Define the scope of the project
      value: "Steps should be taken, which may include all steps or part of a spec development."
    validations:
      required: true
  - type: textarea
    id: Problem-statement
    attributes:
      label: Problem statement
      description: Problem statement
      placeholder: Problem statement
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: Stake-holders
    attributes:
      label: Stake-holders
      description: Stake-holders
      placeholder: Stake-holders
      value: "List GSF members organisations willing to support this Spec."
    validations:
      required: true
